version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    depends_on:
        - master
  master:
    image: jenkinsci/jenkins:latest
    volumes:
      - ./master/jenkins_home:/var/jenkins_home
    expose:
      - "8080"
      - "5000"
  slave0:
    image: jenkinsci/ssh-slave
    depends_on:
      - master
    expose:
      - "22"
    env_file: jenkins_pub_key.env
  slave1:
    image: jenkinsci/ssh-slave
    depends_on:
        - master
    expose:
      - "22"
    env_file: jenkins_pub_key.env

